apiVersion: apps/v1
kind: Deployment
metadata:
  name: __IMAGE_NAME__
spec:
  replicas: 1
  selector:
    matchLabels:
      app: __IMAGE_NAME__
  template:
    metadata:
      labels:
        app: __IMAGE_NAME__
    spec:
      containers:
      - name: __IMAGE_NAME__
        image: __REGISTRY_FQDN__/__IMAGE_VENDOR__/__IMAGE_NAME__:__IMAGE_TAG__
#        env:
#          - name: BLOB_STORAGE_URL
#            value: "file://./mnt/s3?create_dir=true"
        ports:
        - containerPort: 8080
#        volumeMounts:
#        - name: storage
#          mountPath: /mnt/s3
#      volumes:
#      - name: storage
#        flexVolume:
#          driver: "k8s-s3fs"
#          options:
#            endpoint: https://__IMAGE_NAME__-storage.ams3.digitaloceanspaces.com
#            bucket: __S3_BUCKET_NAME__
#            accessKeyID: __S3_ACCESS_KEY__
#            secretAccessKey: __S3_SECRET_KEY__
---
apiVersion: v1
kind: Service
metadata:
  name: __IMAGE_NAME__
spec:
  type: LoadBalancer
  selector:
    app: __IMAGE_NAME__
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: __IMAGE_NAME__-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: caddy
spec:
  rules:
  - host: __IMAGE_NAME__.__FRONT_DOMAIN__
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: __IMAGE_NAME__
            port:
              number: 80
