apiVersion: apps/v1
kind: Deployment
metadata:
  name: sse-shareit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sse-shareit
  template:
    metadata:
      labels:
        app: sse-shareit
    spec:
      containers:
      - name: sse-shareit
        image: registry.digitalocean.com/clockwork-registry/sse-shareit:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sse-shareit
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: sse-shareit
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sse-shareit-ingress
  annotations:
    kubernetes.io/ingress.class: "caddy"
spec:
  rules:
  - host: sse-shareit.do-interview.cw.substance3d.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sse-shareit
            port:
              number: 80
